---
meta:
  name:    prism
  release: Prism Boshrelease
  target:  main@pipes
  url:     https://pipes.starkandwayne.com

  initial_version: 1.0.0

  manifest:
    path: "manifests/prism.yml"
    operator_file_paths: "manifests/operators/credentials.yml" # comma separated list relative to repo root
    vars: ""

  git:
    email: ci@starkandwayne.com
    name:  Stark & Wayne CI Bot

  bosh-lite:
    target:   ((thunder-dome.url))
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cfcommunity.access)) # aws.access_key_id
    secret_key: ((cfcommunity.secret)) # aws.secret_access_key

  github:
    owner:  cloudfoundry-community#starkandwayne
    repo:   prism-boshrelease
    branch: main
    private_key:  ((github.private-key))
    access_token: ((github.access-token))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))
